In [57]:
# Import needed packages
# You may add or remove packages should you need them
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.datasets import load_iris
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.model_selection import KFold, LeaveOneOut, cross_val_score

# Set random seed
np.random.seed(0)

# Display plots inline and change plot resolution to retina
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
# Set Seaborn aesthetic parameters to defaults
sns.set()

In [58]:
# Load the Iris dataset included with scikit-learn
datasets = load_iris()

In [59]:
# Put data in a pandas DataFrame
df_iris = pd.DataFrame(datasets.data, columns=datasets.feature_names)

In [60]:
# Add target and class to DataFrame
df_iris['target'] = datasets.target
df_iris['class'] = datasets.target_names[datasets.target]


In [61]:
# Show 10 random samples
df_iris.sample

<bound method NDFrame.sample of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8

In [62]:
# now... implement the LDA (bear in mind that you do pass it the y's and it is supervised!)
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()


In [100]:
# same process as always, identify your X's and your y's
X = df_iris.drop('target', axis =1).drop('class', axis=1)
y = df_iris['target']
df = df_iris.drop('target', axis =1).drop('class', axis=1)



In [81]:
#train-test-split
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [83]:
scaler = StandardScaler()

scaler = StandardScaler().fit(train_X)
X_train = scaler.transform(train_X)              #Warum davor fitten
X_test = scaler.transform(test_X)
X_train.shape

(120, 4)

In [127]:
# apply the lda transformation
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components=2)
X_train = lda.fit_transform(train_X, train_y)
#X_test = lda.transform(X_test)



ValueError: operands could not be broadcast together with shapes (30,2) (4,) 

In [122]:
# select 2 principal components


In [68]:
# take a look at the new axes for the data and plot them

In [69]:
# what about the variability?

In [143]:
# Run a Random Forest Classifier with the transformed data 
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(max_depth=2)
rf.fit(X_train, y_train)
xrf = rf.predict(X_test)
xrf


array([2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [71]:
#Check the new acuracy! Is it higher or lower than what you obtain selecting 2 features and applying a Random Forest Directly?

In [142]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

sk = confusion_matrix(xrf, y_test)
print(sk)
print(accuracy_score(y_test, xrf))

[[ 0  0  0]
 [ 3  3  1]
 [ 7  6 10]]
0.43333333333333335
